# Generated by Django 2.2.1 on 2019-05-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('height', models.IntegerField(default=-1)),
                ('age', models.IntegerField(default=-1)),
                ('price', models.IntegerField(default=-1)),
                ('picture_url', models.CharField(max_length=50)),
            ],
        ),
    ]
