# Generated by Django 2.2.1 on 2019-05-18 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=-1)),
                ('picture_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='treeitem',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='treeitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='treeitem',
            name='picture_url',
        ),
        migrations.RemoveField(
            model_name='treeitem',
            name='price',
        ),
        migrations.AddField(
            model_name='treeitem',
            name='item_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.ItemDescription'),
            preserve_default=False,
        ),
    ]
