# Generated by Django 2.2.1 on 2019-05-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190518_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdescription',
            name='item_type',
            field=models.CharField(default='tree', max_length=20),
            preserve_default=False,
        ),
    ]
