# Generated by Django 2.2.1 on 2019-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_itemdescription_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('soil', models.CharField(max_length=1)),
                ('sun', models.CharField(max_length=1)),
                ('food', models.CharField(max_length=1)),
                ('water', models.CharField(max_length=1)),
                ('pruning', models.CharField(max_length=1)),
                ('max_height', models.IntegerField(default=-1)),
                ('growth_rate', models.CharField(max_length=1)),
                ('price', models.IntegerField(default=-1)),
            ],
        ),
    ]
