# Generated by Django 2.2.1 on 2019-05-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeitem',
            name='item_info',
        ),
        migrations.DeleteModel(
            name='ItemDescription',
        ),
        migrations.DeleteModel(
            name='TreeItem',
        ),
    ]
